# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60fa5b4b2fb056e75f76fcd22c954e60bcd289d9f43571de7c8d06bc41f3c53d5d061c4e4b5a0b10d5280f7d03e1c7b0de5e691952eeb1931803db975ec2642

test:
  secret_key_base: 3a939b3c015b9d667698d346a4bb75b1a787edabe457a427021b15e3131ec9ec4bf798e71e1773ae20deb1cf1be98976e66d0312b9d8df59906c98d87fd59131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
